server:
  port: 8761
spring:
  application:
    name: service-registry
#  boot:
#    admin:
#      client:
#        url: http://localhost:7777
#        instance:
#          name: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always
    health:
      show-details: always
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 900000
    eviction-interval-timer-in-ms: 60000
  dashboard:
    path: /dashboard
  environment: dev
