server:
  port: 9000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:9095/
          predicates:
            - Path=/users/**
          filters:
            - name: Logging
        - id: order-service-route
          uri: http://localhost:9096/
          predicates:
            - Path=/orders/**
          filters:
            - name: Logging
logging:
  filter:
    includeHeaders: true
    includeBody: true
    logLevel: INFO
  level:
    root: info