server:
  port: 9096
spring:
  application:
    name: project-service
#  boot:
#    admin:
#      client:
#        url: http://localhost:7777
#        instance:
#          name: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
      management.context-path: /actuator
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
